apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  labels:
    app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service-container
          image: senbar/authentication-service:latest
          ports:
            - containerPort: 80
              name: http
        - name: postgres
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: pguser
            - name: POSTGRES_PASSWORD
              value: pgpass
            - name: POSTGRES_DB
              value: pgdb
              # valueFrom:
              #   secretKeyRef:
              #     name: mssql
              #     key: SA_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdb
      volumes:
        - name: pgdb
          persistentVolumeClaim:
            claimName: pg-claim
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: ClusterIP
  selector:
    app: authentication-service
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-claim 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
 

