version: '3.5'

services:
  authorization_service:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "7005:9501"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    volumes:
      - ./var/docker/db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  default:
    external:
      name: external-example