version: '3.5'

services:
  php-swoole-server:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "80:9501"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    volumes:
      - ./var/docker/db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"